grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - ubuntu.local
    path: /
  persistence:
    enabled: true
    type: sts
    accessModes:
      - ReadWriteOnce
    size: 2Gi