services:
  master:
    image: petschenek/ubuntu-systemd:master-${ARCH}-22.04
    build:
      context: ../master-image
      dockerfile: ../master-image/amd64.Dockerfile
    container_name: master
    hostname: master
    privileged: true
    user: root
    stdin_open: true  # Allows the container to stay running
    tty: true         # Enables terminal emulation
    ports:
      - "6443:6443"
      - "8443:8443"
    volumes:
      - "etcd-volume:/var/lib/etcd"
    networks:
      clinco:
        ipv4_address: 172.172.0.1

networks:
  clinco:
    external: true

volumes:
  etcd-volume:
    name: etcd-${ETCD_VOLUME}
    driver: local
